microsoft/Trieste

README.md
There was nothing in the directions that would result in the submodule being pulled in.
=> Fix clone directions

.gitignore, CMakeLists.txt, README.md, samples/verona/lang.cc, samples/verona/lang.h, samples/verona/lookup.cc, samples/verona/parse.cc, samples/verona/readme.md, samples/verona/wf.h, src/ast.h, src/driver.h, src/pass.h, src/rewrite.h, src/source.h, src/token.h, src/wf.h
Symbol tables are now auto-generated from well-formedness annotations. As part of this:
* Well-formedness checks are now enabled with `-w,--wf-check`
* Includes work in a language-agnostic way.
* `TokenDef` can specify which node types can be looked up and looked down, and which shadow lookups in parent scopes.
=> Declarative symbol table generation.

include/trieste/driver.h, include/trieste/parse.h, include/trieste/source.h, include/trieste/wf.h, samples/verona/lang.cc, samples/verona/lang.h, samples/verona/parse.cc, samples/verona/readme.md, samples/verona/std/test.verona, samples/verona/wf.h
The AST emitted by Trieste is prepended with the rewriter name and the pass name that generated that AST. If the rewriter is given a `*.trieste` file, it checks that the rewriter name is the same, and then uses the well-formedness definition for the pass to parse the AST. The rewriter can then proceed from that pass onwards.
This allows the output of any pass to be saved and rewriting to be resumed later.
=> Parse an AST generated by any pass

CMakeLists.txt, README.md
Adding some information to the README on the FetchContent setup, and substituting the git hash for the tag as recommended by the CLI11 authors.
=> Updating the README to include FetchContent information

include/trieste/ast.h, include/trieste/driver.h, include/trieste/wf.h
* Allow proceeding from any AST, regardless of label, that satisfies the parser WF.
* Use netstring encoding for AST node locations, to allow arbitrary characters.
=> Enable Trieste toolchains

include/trieste/wf.h, samples/verona/lang.cc, samples/verona/lang.h, samples/verona/parse.cc, samples/verona/readme.md, samples/verona/wf.h
This uses keywords for `if` and `else` to add conditionals to the Verona sample. This parsing should be the same as if `if` and `else` were programmable control flow, but in fact it's special cased to allow for type checking that knows that only one branch will be executed.
=> Add conditionals to the Verona sample.

include/trieste/ast.h, include/trieste/defines.h, include/trieste/driver.h, include/trieste/pass.h, include/trieste/source.h, include/trieste/token.h, include/trieste/wf.h, samples/verona/lang.cc, samples/verona/lang.h, samples/verona/lookup.h, samples/verona/parse.cc, samples/verona/readme.md, samples/verona/std/test.verona, samples/verona/wf.h
Lambdas are rewritten as anonymous types, so that by the time the ANF pass is running, lambdas no longer exist. This also improves support for conditionals, tracking `move` and `drop` correctly in both branches.
=> Lambdas as anonymous types

include/trieste/ast.h, include/trieste/pass.h, samples/verona/lang.cc, samples/verona/readme.md, samples/verona/wf.h
If a class has no `create` function, this generates one, using field default values as `create` parameter default values.
=> Autogenerate create functions

samples/verona/lang.cc, samples/verona/readme.md
You can use `_` (DontCare) as a parameter name (where it will get a fresh identifier, and so be unnameable), and you can use it in an expression, where it becomes `let _`, where `_` is again a fresh identifier.
=> Use _ to ignore a parameter or a binding

samples/verona/lang.cc, samples/verona/readme.md
A `ClassBody` is already used to define a `class` or an anonymous structural type. Now, `new` followed immediately by `{ ... }` is an object literal, where the `ClassBody` defined by `{ ... }` is a new anonymous class.
=> Object literals

CMakeLists.txt, include/trieste/driver.h, include/trieste/gen.h, include/trieste/parse.h, include/trieste/wf.h, include/trieste/xoroshiro.h, samples/verona/CMakeLists.txt, samples/verona/lang.cc, samples/verona/parse.cc, samples/verona/readme.md
In your parser, you can specify generator functions for specific AST node types. This is only used during testing, when generating synthetic AST nodes.
=> Allow custom locations when generating a synthetic AST

include/trieste/ast.h, include/trieste/driver.h, include/trieste/pass.h, samples/verona/lang.cc, samples/verona/lang.h, samples/verona/readme.md, samples/verona/wf.h
This allows conditionals of the form:
```
if expr
{
x: T -> ...
}
```
Instead of `expr` being evaluated for truthiness, the lambda only executes if `expr` has a dynamic type that is a subtype of `T`.
=> Add TypeTest conditionals

CMakeLists.txt
Projects which include Trieste currently always build `fmt` (because of how they added the target) even if it was unneeded. This fixes it so that it will only be built by projects which have it as a dependency (e.g. Verona)
=> Removing fmt target from all

CMakeLists.txt, include/trieste/gen.h, include/trieste/parse.h, include/trieste/regex.h, include/trieste/rewrite.h, include/trieste/wf.h, samples/infix/CMakeLists.txt, samples/verona/CMakeLists.txt, samples/verona/parse.cc, samples/verona/readme.md
This switches from the `stl` regex implementation to `RE2`. While we're no longer able to use predicates or back-references, regex parsing is significantly faster.
=> switch to RE2

include/trieste/wf.h
I'm reasonably certain the current logic means that all well-formed checks will pass, as the final return value ignores the `ok` variable.
=> Fixing a bug in the well-formed check

include/trieste/wf.h
In cases where a Fields contained one or more Error nodes, the WF checker would still perform the count check. Also, it was not returning the value of `ok` as determined by the child checks.
=> Fix for Fields WF check.

include/trieste/wf.h
GCC is more pedantic by default on using std::move to prevent unnecessary copies.
=> Add some useful `std::move`s

include/trieste/ast.h, include/trieste/rewrite.h
It is often advantageous to create a unique variable with a recognisable name to aid in debugging. This PR adds an optional prefix to the `fresh()` call to make this easier.
=> Adding prefix to fresh names.

CMakeLists.txt, samples/infix/CMakeLists.txt, samples/verona/CMakeLists.txt
This minor change to the CMake configuration makes it so that `trieste` exports the targets of its dependencies in addition to its own, as well as making the dependency relationship explicit. The result of this is that projects which use `trieste` no longer need to explicitly link its dependencies, but rather can just link `trieste::trieste`, like so:
```cmake
target_link_libraries(myproject PUBLIC trieste::trieste)
```
=> Exporting CMake dependencies.

include/trieste/wf.h
This is my attempt at adding this feature. It addresses the problem at the cost of adding the index to the `struct`, thus allowing the `lookup_replace` call to still have access to the correct in-place `Node&` reference.
=> Attempt to allow `const Node&` for creating `WFLookup` objects

include/trieste/wf.h, samples/infix/wf.h
This allows you to write `Choice - Choice` or `Choice - Token` to create a new `Choice` in your wellformedness definition.
=> Add an operator for removing elements from a WF choice

include/trieste/pass.h
This converts the `PassDef::apply` to be iterative rather than recursive.
=> Convert `apply` to be iterative.

include/trieste/ast.h, include/trieste/wf.h
This PR is about closing off a fairly damaging erroneous usage of the Trieste API. As currently written, client code can write:
```cpp
node->back() = new_node;
```
Because `back()` is a `Node&`, this call will actually change the last child of the node, but circumvent the setting of the parent. The result is that the previous child still points to `node` as its parent, and the new child has a `nullptr` parent. If `node` is then subsequently deleted, the old child still has a pointer to it and this can result in a use-after-free. The new approach is to close this functionality by making these `const Node&` and also changing the iterator to be a const iterator.
To help ease issues where this functionality was needed, I've also added a `replace_at` method which provides a way of replacing a …
=> Issue with `Node&` allowing parent circumvention

include/trieste/ast.h
Error node needs to be checked for explicitly as the flag is not set on error nodes.
=> Fix error nodes.

include/trieste/ast.h, include/trieste/driver.h, include/trieste/logging.h, include/trieste/parse.h, include/trieste/regex.h, include/trieste/wf.h
This PR creates a logging/tracing library for Trieste to use.  This can then be used by downstream projects such as rego-cpp and verona. The intent is to reduce the cost of checking whether log should be generated.
There is a pure C++ approach to using the library
```C++
trieste::logging::Info() << "Hello " << 5;
```
that will output a log message if the `Info` level should be printed.  The messages are output on destruction of the `Log` object, so that there is no tearing in a concurrent setting.
The log object can also be a local variable to allow more complex messages to be constructed.
```C++
trieste::logging::Info out;
out << "Hello" << trieste::logging::Indent;
for (int i = 0; i < 10 ; i++)
out << "i = " << i << std::endl; 
out << trieste::logging::Undent;
out << "Goodbye.";
``` …
=> Logging in Trieste

samples/infix/lang.cc
Looking up an identifer duplicates a node. This requires an explicit clone.
=> Missing clone in infix example

.github/workflows/buildtest.yml
This issue is causing the Clang build to fail. This moves the CI to using clang++-15 to address the issue:
https://github.com/actions/runner-images/issues/8659
=> Fix for https://github.com/actions/runner-images/issues/8659

include/trieste/logging.h
On some platforms (notably musllinux) the comparison changed in the PR causes an compiler error about assuming a cast on f. The committed change fixes that compiler error without any change in functionality.
=> Fix for "assuming cast" compiler error on comparison to std::endl.

.clang-format, .github/workflows/buildtest.yml, CMakeLists.txt, include/trieste/ast.h, include/trieste/utf8.h, include/trieste/wf.h, parsers/CMakeLists.txt, parsers/include/trieste/json.h, parsers/json/CMakeLists.txt, parsers/json/emitter.cc, parsers/json/json.cc, parsers/json/parse.cc, parsers/json/reader.cc, parsers/test/CMakeLists.txt, parsers/test/json_test.cc, parsers/test/json_trieste.cc
This code acts as both additional sample code and also as a fully-functional JSON parser and emitter. In addition to the standard Trieste tests it also includes a test driver which runs tests from https://github.com/nst/JSONTestSuite to insure full RFC 8259 compliance.
Further, this PR adds a UTF-8 header to Trieste which provides a range of useful Unicode parsing and conversion functions.
=> Adding a JSON parser based on Trieste

.github/workflows/buildtest.yml, CMakeLists.txt, include/trieste/ast.h, include/trieste/pass.h, include/trieste/wf.h, parsers/json/json.cc, parsers/json/parse.cc
The rewrite engine used an efficient path based traversal that was iterative with effectively pre and post-order actions.  This PR factors that into ast.h, and then uses it for various operations to prevent stack overflow on deep asts.
It also fixes the recursive delete problem that you get from shared_ptr, by building a work list of nodes that need to be destructed.
=> Fix recursive stack depth problems.

include/trieste/ast.h
The traverse function was calling post(root) twice:
once just before exiting the loop, and
once just after the loop.
This removes the unneccessary additional call.
=> Fix to #309

include/trieste/parse.h, include/trieste/reader.h
The previous driver took a directory as well as an individual file. This reinstates this behaviour.
=> Fix Reader to take a directory

include/trieste/debug.h, include/trieste/parse.h, include/trieste/pass.h, include/trieste/rewrite.h
As several parts of Trieste are dynamic the debugging experience can be a challenge. This uses source_location to provide more information about where a particular rule is defined in the source.
=> Add source_location to help with debugging.

include/trieste/ast.h
* Add a `str` that returns a string.
* Make `set_location` use `traverse`.  Any tree traversal should use `traverse` to handle very large graphs.
=> Two small changes to the ast

include/trieste/parse.h
This PR adds a single function to the `Make` class that allows checking the type of the parent of the current group during parsing. Just as `m.in(Foo)` returns true if the cursor is in a `Foo` node, `m.group_in(Foo)` returns true if the cursor is in a group which in turn is in a `Foo` node. 
A concrete use case for this is being able to parse lists with prefix separator:
```sml
match n with
| 0 -> "zero"
| 1 -> "one"
| _ -> "a lot"
```
For _infix_ separators we can use `seq(Bar)` to push the current group under some separator. This is the behaviour we want for the second and third `|` above, but for the first `|` `seq(Bar)` will make the group `match n with` a child of the first `|`. Instead, we want to do `push(Bar)` for the first `|`, but using that for the latter ones will nest the …
=> Added parser support for checking parent of current group

parsers/json/reader.cc, parsers/yaml/internal.h
The Python wheel building system on CentOS objects to these semicolons.
=> Removing stray semicolons

CMakeLists.txt, include/trieste/parse.h, include/trieste/source.h, samples/infix/CMakeLists.txt, samples/infix/infix.cc
This commit adds a check for large files (> 64kb) to check that they are valid inputs. Previously, Trieste would try to read an input file into main memory as a string, regardless of whether that file actually contains something the parser will consider valid. With this change, Trieste will first try parsing the first 4kb of any file over 64kb to see if the parser largely accepts it, and only then continue parsing the rest of the file.
=> Large file validity check.

parsers/json/parse.cc
Very large JSON files will have residual stack values (due to the preview check) which were not clear, meaning that they could not successfully parse.
=> Fix for large JSON files

include/trieste/parse.h, include/trieste/source.h
My previous attempt at dealing with large files had trouble with large files which contained significant segments of invalid tokens sequestered within a string literal at the beginning of the file (where I performed my preview). This necessitated a different approach. This new solution has the advantage of both being simpler (just based on error counting) and also being robust to this sort of problem.
=> Dealing with large files

include/trieste/pass.h, include/trieste/rewrite.h, include/trieste/wf.h
See issue #115 for more discussion.
The key idea here is to use the `SNMALLOC_SLOW_PATH` macro, which is a cross-plaform noinline macro, on functions which construct, copy, and destroy long-lived pass, pattern, and WF objects.
These functions are only called on start-up, so they should have minimal performance impact.
By default, they are inlined into Trieste pass defs and such.
Some of their contents is rather bulky, like red-black tree copy routines, big reference count updates (including dynamic checks for whether glibc is multi- or single- threaded), and array resizing code.
Making these lifecycle functions explicit using `= default` and marking them with `SNMALLOC_SLOW_PATH`, alongside some other operators that might possible cause similar problems, saves 15-27% on code size for …
=> Binary size improvements related to #115

CMakeLists.txt, include/trieste/ast.h, include/trieste/intrusive_ptr.h, include/trieste/parse.h, include/trieste/pass.h, include/trieste/regex.h, include/trieste/rewrite.h, include/trieste/source.h, include/trieste/token.h, include/trieste/writer.h, parsers/yaml/reader.cc, parsers/yaml/writer.cc, test/CMakeLists.txt, test/intrusive_ptr_test.cc
This proposed change relates to the ongoing discussion of #115, regarding how Trieste can reduce its impact on binary size.
One thing we identified was the footprint of shared_ptr destructors, which will be included whenever the ubiquitous `Node` goes out of scope. We considered switching to a customized intrusive reference counted pointer implementation, which might be a bit more efficient, and would give us more control over code generation of such a common case in code that uses Trieste.
The resulting pointer implementation, and its non-inline refcount decrement, saves 300KB on the `yamlc` executable, and saved 1.3MB on rego-cpp's main executable, or about 20% of its original size (6.8MB). Keeping the refcount decrement inlineable (but otherwise the same) saves some space still, but …
=> Use intrusive reference counting

.github/workflows/buildtest.yml, CMakeLists.txt, test/CMakeLists.txt
Does what the title says.
I noticed when trying to update rego-cpp that the tests, when auto-run from a dependency, fail because they can't find their executables.
This didn't show up before because Trieste did not itself have tests until I added this last set (all tests were indirect and optional, part of the tools).
It might actually be more reasonable to disable running tests when included as a dependency, but I'm not sure how to do that. Looking around on the internet, with my search terms at least, is inconclusive.
This change on its own at least makes sure the tests can be launched correctly regardless of context.
=> Fix intrusive_ptr test breakage in dependencies

include/trieste/ast.h, include/trieste/parse.h, include/trieste/regex.h, include/trieste/rewrite.h, include/trieste/wf.h, parsers/yaml/reader.cc, parsers/yaml/writer.cc, test/CMakeLists.txt
Based on a recent discussion that was left out of scope of #128, there was an idea to make `->parent()` return a `Node` rather than require callers to use `shared_from_this` (or `intrusive_ptr_from_this` now).
This PR makes that change. It:
- changes `parent()` to return `Node`
- adds `parent_unsafe()` that keeps old behavior if you don't want refcounting overheads and you know your borrow is safe
Point of discussion: what do we do with original calls to `parent`? Do all those calls in YAML change type, or do we make them `parent_unsafe`? I'm told it might have performance implications. So far, I only made `->parent()->intrusive_ptr_from_this()` into `->parent()` and otherwise went the unsafe route, but there's plenty of room for "don't care keep it simple" in other cases.
~~There's also …
=> Make parent() return a Node

CMakeLists.txt, include/trieste/source.h, parsers/yaml/event_writer.cc, parsers/yaml/to_json.cc, test/CMakeLists.txt, test/source_test.cc
This PR is split off from #126, because really it's an orthogonal fix.
The observed problem was that, on Windows, error messages had a strange `\r` in reported source locations that was inconsistent with both other platforms, and other parts of the same output string (you would see `\n` once then `\r\n` further along the same string).
The trouble was traced back to `source.h`, which was separating lines based on only the `\n` character, and assuming that line breaks were only 1 char wide. This PR rewrites the 3 line/columns handling functions that did this, so that they will accept `\r\n`, `\n`, and `\r` as line delimiters while reporting correct line lengths (and so forth) on all platforms.
The main change of substance is that the `lines` field of `SourceDef` changes from a vector of …
=> Let Location::str() handle `\r` correctly

parsers/yaml/parse.cc, parsers/yaml/reader.cc
- The error for the document start marker `---` in a double quoted string was stricter than needed. This has been loosened to allow for a wider range of strings
- Comments after the document start marker before a mapping were causing issues with the whitespace logic. This has been resolved.
- Fixed an issue with comments within complex key constructions in flow mappings
- Fixed an issue with trailing comments in flow sequences
=> Fixing some YAML corner cases

include/trieste/pass.h, include/trieste/token.h
This PR adds an effect `Reapply` that makes matching continue at the newly inserted node(s). It is intended to be used in `once` passes for "local fixpoint" computations but can be used with non-`once` passes as well. `Reapply` works like `Seq` in that the node is replaced by all of its children. As an example, consider the rewrite rules
T(A) * T(A) >> [](auto&) -> Node { return B; }
T(B) * T(A) >> [](auto&) -> Node { return C; }
When run in a `once` pass they would turn "**A A** A" into "B A". Changing the effect in the first rule to `return Reapply << B` would make the rewrites in sequence be "**A A** A ~> **B A** ~> C". Of course, careless use of `Reapply` can make a `once` pass loop forever.
Closes #139.
=> Support for Reapply effect

CMakeLists.txt
Using FetchContent adds all the subprojects build targets. This removes those targets using a slightly different way of including the directories that uses `EXCLUDE_FROM_ALL`.
This should reduce the number of build targets exposed.
=> Updated uses of FetchContent

include/trieste/wf.h
This PR adds support for removing shapes from a WF specification:
```
inline const auto wf1 =
(Foo <<= Bar++)
| Baz <<= Foo * Bar
;
inline const auto wf2 =
(wf1 - Foo)
| Bar <<= Baz++
```
In `wf2` `Foo`s can still appear in the tree, but they must have zero children (just like if they were never in the WF to begin with). Without this PR, the only way to achieve the same functionality is by repeating the shape list without `Foo`.
To be honest, I'm not sure what I'm doing with the functions taking rvalues, I'm just parroting other similar functions.
=> Add support for removing shapes from WF specifications

samples/shrubbery/CMakeLists.txt
Removes a line from `CMakeLists.txt` in the shrubbery sample that was left there by accident.
=> Remove target from shrubbery sample's CMake file

include/trieste/driver.h
In the ```run()``` method in ```driver.h```, the "```test_start_pass"``` for fuzzing was previously selected as ```test_start_pass = pass_names.at(1);``` which gives the second pass after the parser but compensates for the initial pass being the pass at  ```start_index - 1``` in the method ```test()``` in the ```Fuzzer``` class.
However, the start_index for the returned ```Fuzzer``` object returned from ```reader.pass_index()``` compensates in the other direction and adds +1 to the pass index, meaning the first pass in the pass sequence in the reader does not get tested if not given explicitly.
```
return Fuzzer(reader)
...
.start_index(reader.pass_index(test_start_pass))
...
.test();
```
I just added the minimal fix to start fuzz testing from the first pass as default, but perhaps the …
=> Fuzzer started from second instead of first pass as default when using Driver

include/trieste/wf.h, parsers/json/internal.h
This PR adds support for giving upper bounds for sequences in the well-formedness specifications:
```
inline const auto some_wf =
(File <<= Group++) // Zero or more groups
| (Foo <<= Group++[1]) // One or more groups
| (Bar <<= Group++[1][3] // Between one and three groups
```
One motivating use case is having a top-level optional shape (which is shorthand for `++[0][1]`):
```
inline const auto foo_wf =
some_wf
| (Paren <<= ~(Foo | Bar)) // Optionally contains a single Foo or a single Bar
```
Before this, the closest you could get was using `++`, which would mess with fuzz testing. Just as sequences, optional shapes can only be used at the top level of a shape; you still cannot write e.g. `Paren <<= Foo * ~Bar` or `Paren <<= Foo * Bar++`.
The JSON parser had `File <<= Group++` even though …
=> Added upper bounds for sequences

include/trieste/parse.h, samples/shrubbery/parse.cc
This PR adds two things to the parser API:
* Versions of `in` and `group_in` that takes a list of tokens, for checking if we are in one of several kinds of nodes.
* A version of `pop` that takes no argument, blindly popping from whatever node we are in and returning its token.
I find myself often wanting to implement "keep popping until we are no longer in one of these things" or "keep popping until we are inside one of these things". This makes that kind of logic simpler to implement (see diff of shrubbery parser for an example).
=> Updated parser API with convenience in and blind pop

include/trieste/wf.h
This PR fixes #140. You could get an out-of-bounds error when populating symbol tables if you generated a node with a binding (e.g. `(Assign <<= Ident * Expr)[Ident])`) with too few children. The solution here is to abort early and pretend that everything is fine. This allows checking for errors (maybe the binding was malformed due to the presence of errors) and relies on the WF check to reject the tree later. You cannot simply do the WF check first since that also checks that bindings have a corresponding entry in a symbol table.
=> Check indexing when binding symbols

CMakeLists.txt, parsers/json/CMakeLists.txt, parsers/test/CMakeLists.txt, parsers/yaml/CMakeLists.txt, samples/infix/CMakeLists.txt, samples/shrubbery/CMakeLists.txt, test/CMakeLists.txt
Instead of setting Warnings/Werror on the trieste interface target, which means that any code using the target picks up the flags, this PR is restricting it to the binaries built by the project (tests and sample parser libraries).
This is so that projects that use Trieste, directly and otherwise, as well as other code that is not necessarily warning-free, and that those other projects may not control, can build binaries effectively.
I have diffed the output of `ninja -j1 -v`, pre and post change, to make sure I did not miss anything. Note that projects depending on Trieste, such as https://github.com/microsoft/rego-cpp/ will need to do something similar, to keep building their tests/binaries with Warnings/Werror.
=> Do not export warning flags, but apply them to all targets the project builds

CMakeLists.txt
Bumping the version of CLI11 to the latest. This will fix the warnings (and now errors on some platforms) about CMake 3.5 being deprecated.
=> Updating to the latest version of CLI11
